### ISSUE TITLE
Prefer using the LGPL

### ISSUE THREAD

**Issue by zephyr111** [netorcai/netorcai-client-d#1]
It should be better to use the LGPL for this project since the examples are in public domain.
Indeed, with the GPL, the copyleft apply to the examples and more generally all "derived works".
See https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works.

Also note that the GPL itself states:
```
The GNU General Public License does not permit incorporating your program
into proprietary programs.  If your program is a subroutine library, you
may consider it more useful to permit linking proprietary applications with
the library.  If this is what you want to do, use the GNU Lesser General
Public License instead of this License.  But first, please read
<http://www.gnu.org/philosophy/why-not-lgpl.html>.
```

**Comment by mpoquet** [comment]
Changed in 7401227. Thanks!
